---
- hosts: all
  tasks:
    - name: Ensure tox is present
      include_role:
        name: ensure-tox

    - name: Run molecule tests on tox
      include_role:
        name: tox
      vars:
        tox_extra_args: "-vv -- {{ kubernetes_core_molecule__test_scenario }}"
        zuul_work_dir: "~/.ansible/collections/ansible_collections/kubernetes/core"
        tox_install_siblings: false
