---
- hosts: all
  tasks:
    - name: Ensure Kubernetes cluster
      include_role:
        name: setup-kind

    - set_fact:
        virtualenv_path: "~/venv"

    - name: Create virtualenv used to install collection
      shell: "virtualenv {{ virtualenv_path }}"

    - name: Upgrade pip
      shell: "{{ virtualenv_path }}/bin/pip install --upgrade pip"

    - name: Install Ansible into virtualenv
      environment:
        ANSIBLE_SKIP_CONFLICT_CHECK: 1
      shell: "{{ virtualenv_path }}/bin/pip install ansible 'jinja2<3.0.0'"

    - name: Fetch and install the artifacts
      import_role:
        name: deploy-artifacts

    - name: Debug list tox environment
      command: tox -a
      args:
        chdir: ~/.ansible/collections/ansible_collections/kubernetes/core
      register: _result

    - debug: var=_result

    - name: Run molecule tests using tox
      include_role:
        name: tox
      vars:
        tox_install_siblings: false
