---
- hosts: controller
  tasks:
    - name: Test using Molecule
      shell: "source {{ ansible_test_venv_path }}/bin/activate; molecule test"
      environment: "{{ ansible_test_environment | default({}) }}"
      args:
        chdir: ~/.ansible/collections/ansible_collections/kubernetes/core
