---
- name: Create Kubernetes cluster on appliance
  hosts: openvswitch
  gather_facts: false
  tasks:
    - name: Run ensure-docker role
      import_role:
        name: ensure-docker

    - name: Setup k8s cluster
      import_role:
        name: setup-kind
      vars:
        kind_cluster_ip: "{{ hostvars['kubernetes']['nodepool']['interface_ip']}}"

    - name: Fetch Kube config from cluster
      fetch:
        src: "~/.kube/config"
        dest: "{{ zuul.executor.work_root }}/config"
        flat: true

- hosts: controller
  tasks:
    - name: Ensure controller directory exists
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs/controller"
        state: directory

    - name: create directory for kube configuration
      file:
        state: directory
        path: "~/.kube"

    - name: copy kube configuration file into destination path
      copy:
        dest: "~/.kube/config"
        src: "{{ zuul.executor.work_root }}/config"
