---
- hosts: all
  tasks:
    - name: Ensure controller directory exists
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs/controller"
        state: directory

    - name: Run ensure-docker role
      include_role:
        name: ensure-docker

    - name: Setup ensure-tox role
      include_role:
        name: ensure-tox

    - name: Install SELinux Python bindings using yum
      yum:
        name: libselinux-python3
        state: present
      become: true
      when:
        - ansible_os_family == "RedHat"

    - name: Fetch and install the artifacts
      import_role:
        name: deploy-artifacts
      when:
        - ansible_test_kubernetes_with_cluster | default(True)

    - name: Install Kubernetes cluster
      include_role:
        name: setup-kind
      when:
        - ansible_test_kubernetes_with_cluster | default(True)
