---
- hosts: all
  tasks:
    - name: Ensure tox
      include_role:
        name: ensure-tox

    - name: Run ensure-docker role
      include_role:
        name: ensure-docker

    # tox -e sanity -vv -- 3.7
    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_envlist: sanity
        tox_extra_args: 3.7 -vv
        tox_install_siblings: false
        zuul_work_dir: "{{ zuul.projects['github.com/ansible-collections/kubernetes.core'].src_dir }}"

    - name: Fetch and install the artifacts
      import_role:
        name: deploy-artifacts
      vars:
        deploy_artifacts_venv_path: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible-collections/kubernetes.core'].src_dir }}/.tox/venv"

    - name: Install kubernetes cluster
      include_role:
        name: setup-kind
