---
- hosts: all
  tasks:
    - name: Ensure controller directory exists
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs/controller"
        state: directory

    - name: Run ensure-docker role
      include_role:
        name: ensure-docker

    - name: Setup ensure-tox role
      include_role:
        name: ensure-tox

    - name: Install SELinux Python bindings using yum
      yum:
        name: libselinux-python3
        state: present
      become: true

    - name: Install Kubernetes cluster
      include_role:
        name: setup-kind
      when:
        - ansible_kubernetes_cluster_required | default(True)
