---
- name: Create Kubernetes cluster on appliance
  hosts: openvswitch
  gather_facts: false
  tasks:
    - name: Run ensure-docker role
      import_role:
        name: ensure-docker

    - name: Setup k8s cluster
      import_role:
        name: setup-kind
      vars:
        kind_cluster_ip: "{{ hostvars['kubernetes']['nodepool']['interface_ip']}}"

    - name: Fetch Kube config from cluster
      fetch:
        src: "~/.kube/config"
        dest: "{{ zuul.executor.work_root }}/config"
        flat: true

- hosts: controller
  tasks:
    - name: Ensure controller directory exists
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs/controller"
        state: directory

    - name: Run ensure-virtualenv role
      include_role:
        name: ensure-virtualenv

    - name: Run ensure-pip role
      include_role:
        name: ensure-pip

    - name: Setup base virtualenv_options
      set_fact:
        _virtualenv_options: "--python python{{ ansible_test_python }}"

    - name: Ensure pip temp directory exists in /var/tmp
      file:
        state: directory
        path: /var/tmp/ansible-test-pip

    - name: Create virtualenv for ansible-test
      shell: "virtualenv {{ _virtualenv_options }} {{ ansible_test_venv_path }}"

    - name: Upgrade pip
      shell: "{{ ansible_test_venv_path }}/bin/pip install --upgrade pip"

    - name: Install Ansible into virtualenv
      environment:
        ANSIBLE_SKIP_CONFLICT_CHECK: 1
        TMPDIR: /var/tmp/ansible-test-pip
      shell: "{{ ansible_test_venv_path }}/bin/pip install {{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"

    - name: Fetch and install the artifacts
      import_role:
        name: deploy-artifacts

    - name: Install molecule and collection dependencies
      pip:
        name:
          - yamllint
          - kubernetes
          - flake8
          - jsonpatch
        virtualenv: '{{ ansible_test_venv_path }}'
        virtualenv_python: python3

    - name: Disable selinux with selinux_please_lie_to_me
      shell: |
        {{ ansible_test_venv_path }}/bin/pip uninstall -y selinux
        {{ ansible_test_venv_path }}/bin/pip install selinux_please_lie_to_me

    - name: copy test playbook
      copy:
        src: play.yaml
        dest: /tmp/play.yaml
