---
- hosts: all
  vars:
    ansible_artifacts_path: "~/artifacts"
  tasks:
    - name: Find existing tarballs in folder
      find:
        file_type: file
        paths: "{{ ansible_artifacts_path }}"
        patterns: "redhat-openshift-*.tar.gz"
      register: result

    - name: Delete existing tarballs
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ result.files }}"

    - name: Build an ansible collection
      args:
        chdir: "{{ zuul_work_dir }}"
      shell: "make downstream-build"

    - name: Find existing tarballs in folder
      find:
        file_type: file
        paths: "{{ zuul_work_dir }}"
        patterns: "redhat-openshift-*.tar.gz"
      register: openshift_artifact

    - debug: var=openshift_artifact

    - name: Copy redhat.openshift tarball into artifact directory
      copy:
        src: "{{ item.path }}"
        dest: "{{ ansible_artifacts_path }}"
      with_items: "{{ openshift_artifact.files }}"
