---
- hosts: all
  vars:
    ansible_artifacts_path: "~/artifacts"
  tasks:
    - name: Find existing tarballs in folder
      find:
        file_type: file
        paths: "{{ ansible_artifacts_path }}"
        patterns: "redhat-openshift-*.tar.gz"
      register: result

    - name: Delete existing tarballs
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ result.files }}"

    - name: Build an ansible collection
      args:
        chdir: "{{ zuul_work_dir }}"
      shell: "make downstream-build && mv redhat-openshift-*.tar.gz {{ ansible_artifacts_path }}"
