---
- name: Identify the targets associated with the changed files
  include_tasks: ansible_test_changed.yaml
  when: ansible_test_splitter__test_changed|bool

- name: Build a list of all the targets
  include_tasks: list_all.yaml
  when: not(ansible_test_splitter__test_changed|bool)

- name: Split targets
  include_tasks: split_targets.yaml
