---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - kubernetes.core
  
  tasks:
    - name: Create simple namespace
      k8s:
        kind: Namespace
        name: testing-collection
